name: shangrila
description: ShangriLa Group Application

# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.0+1

environment:
  sdk: ">=2.17.6 <3.0.0"

dependencies:
  flutter_localizations:
    sdk: flutter
  flutter:
    sdk: flutter
  
  cupertino_icons: ^1.0.3
  intl: ^0.17.0
  http: ^0.13.3
  mockito: ^5.0.14
  json_annotation: ^4.0.1
  english_words: ^4.0.0
  dio: ^4.0.0
  table_calendar: ^3.0.2
  flutter_calendar_carousel: ^2.0.3
  charts_flutter: ^0.12.0
  syncfusion_flutter_datepicker: ^20.2.45
  syncfusion_flutter_calendar: ^20.2.45
  syncfusion_flutter_charts: ^20.2.45
  pdf: ^3.4.2
  path_provider: ^2.0.2
  time_range: ^1.0.0
  image_picker: ^0.8.3+2
  date_time_picker: ^2.1.0
  flutter_datetime_picker: ^1.5.1
  package_info: ^2.0.2
  shared_preferences: ^2.0.6
  flutter_html: ^2.1.1
  url_launcher: ^6.0.9
  qr_code_scanner: ^1.0.1
  flutter_screenutil: ^5.0.0+2
  firebase_core: ^1.6.0
  firebase_database: ^9.1.2
  firebase_messaging: ^12.0.3
  flutter_local_notifications: ^9.1.4
  notification_permissions: ^0.6.1
  number_inc_dec: ^0.8.0
  google_maps_flutter: ^2.0.9
  location: ^4.3.0
  qr_flutter: ^4.0.0
  carousel_slider: ^4.0.0
  geolocator: ^9.0.1
  chewie: ^1.2.2
  video_thumbnail: ^0.5.2
  external_path: ^1.0.1
  file_picker: ^5.0.1
  fluttertoast: ^8.0.8
  flutter_dialogs: ^3.0.0
  flutter_downloader: ^1.7.1
  # only IOS gallery_saver: ^2.3.2
  flutter_app_badger: ^1.3.0
  square_in_app_payments: ^1.7.2
  uuid: ^3.0.3
  flutter_linkify: ^5.0.2

  maps_launcher: ^2.0.1

dev_dependencies:
  flutter_test:
    sdk: flutter

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:

    - images/login_back.jpg

    - images/no_image.jpg

    - images/logo.png
    - images/card_back.png
    - images/home_body_back.jpg

    - images/cart_back.jpg
    - images/qr_logo.png
    - images/icon/icon_diamond.png
    - images/icon/icon_person.png

    - images/footer_back.png
    - images/icon/icon_home.png
    - images/icon/icon_back.png
    - images/icon/icon_forward.png
    - images/icon/icon_setting.png
    - images/icon/icon_logout.png
    - images/icon/icon_footer_cart.png
    - images/icon/person.png

    - images/pattern/border_dotted.png
    - images/pattern/line_slash.png
    - images/pattern/card_right_bargroup.png

    - images/icon/icon_calancer.png
    - images/icon/icon_checkin.png
    - images/icon/icon_messeage.png
    - images/icon/icon_brush.png
    - images/icon/icon_cart.png
    - images/icon/icon_card.png
    - images/icon/icon_history.png
    - images/icon/icon_organlist.png
    - images/icon/icon_advise.png
    - images/icon/icon_sale.png
    - images/icon/icon_blog.png

    - images/organ_back.jpg
    - images/organ_floor_match.png
    - images/organ_map_bar.jpg

  fonts:
    - family: Bauhaus93
      fonts:
        - asset: fonts/Bauhs93.ttf
        - asset: fonts/Bauhaus-93-Regular.ttf
 
    - family: Amazon
      fonts:
        - asset: fonts/amazone_bt.ttf
    
    - family: Hiragino
      fonts:
        - asset: fonts/Hiragino-Sans-GB-W6.ttf

    - family: KozGoPr6
      fonts:
        - asset: fonts/KozGoPr6NRegular.ttf